### ISSUE TITLE
what files do I use to install this?

### ISSUE THREAD

**Issue by roland49** [enollo/woocommerce-google-trusted-stores-integration#8]
I've downloaded woocoomerce-google-trusted-stores-integration.zip.
The zip file contains:
readme.txt
woocoomerce-google-trusted-stores-integration.php
Folder: /includes

What do I upload to me wordpress site?

**Comment by tamarazuk** [comment]
You can just install the .zip file you downloaded via your WordPress admin (Plugins > Add New) or you can unzip and upload the entire folder via FTP. Let me know if that helps.
