### ISSUE TITLE
Optional: Google Shopping Item ID is missing?

### ISSUE THREAD

**Issue by HotShotsSecret** [enollo/woocommerce-google-trusted-stores-integration#9]
How to Fix: Provide the Google Shopping Item ID in the “google_base_offer_id” field of the Google Trusted Stores JavaScript code.

**Comment by ideawebservices** [comment]
The Google Shopping Item ID will only show on single product pages.  If you go to a product page and run the test, you shouldn't get that message about it being missing.  You will get that message on any non-single product page since there is no single item id to send.

**Comment by HotShotsSecret** [comment]
Ok great, that worked on the product pages for the badge code! Still a similar warning for the Order confirmation module, though...

**Comment by ideawebservices** [comment]
What is the warning you are getting for the order confirmation module?

**Comment by HotShotsSecret** [comment]
Last result collected from
https://www.hotshotsecret.com/checkout/order-received/-----/?key=wc_order_-------------&utm_nooverride=1

Optional: Google Shopping Item ID is missing
How to Fix: Provide the Google Shopping Item ID in the “google_base_offer_id” field of the Google Trusted Stores JavaScript code.

**Comment by ideawebservices** [comment]
Oh I see, yes, that's the same warning.  The Google Shopping Item ID is only passed on single product pages, so you will get that warning on the order confirmation page and all other pages of the site that are not single product pages.
